# Use an official OpenJDK 17 image as a parent image
FROM azul/zulu-openjdk:17

# Set the working directory to /app
WORKDIR /app

# Copy the pom.xml file first to leverage Docker caching
COPY pom.xml .

# Download and install Maven dependencies
RUN apt-get update && \
    apt-get install -y maven && \
    mvn dependency:go-offline

# Copy the project files
COPY . .

# Build the JAR file
RUN mvn package

EXPOSE 8761
EXPOSE 8762

# Specify the command to run on container startup
CMD ["java", "-jar", "target/eureka_server-0.0.1-SNAPSHOT.jar"]
